### ISSUE TITLE
동일 아이디 중복 로그인에 대한 처리방식 논의

### ISSUE THREAD

**Issue by cyzest** [bluemirr5/toychat#5]
채팅 서비스의 특성상 동일 아이디로 중복 로그인 시
기존 접속을 해제 할 것인지?
기존 접속을 유지하고 로그인을 막을 것인지?
혹은 동일 아이디 라고 하더라도 멀티 접속을 허용 할 것인지?

현재 채널사용자관리 로직흐름으론 멀티 접속을 하게 되면
동일 아이디에 대해서 접속자가 한명으로 보이게 되는 이슈가 있다.

**Comment by bluemirr5** [comment]
회원 정보에 설정정보 넣는건 어때요? default 설정은 기존접속을 유지하고 로그인 막게 해놓고 로그인 한 후에 자기 정보에서 설정으로 중복해서 로그인들어올시 기존 접속을 해제할것인가 기존접속을 유지하게 할것인가를 라디오버튼같은걸로 설정하게끔. 멀티 접속은 좀 정신 없을것 같아서...

**Comment by cyzest** [comment]
그렇게 하는게 가장 안전할 꺼 같네요 ㅋㅋ
여타 다른 채팅도 채팅개념에 동일 아이디로 여러곳에 접속하는 개념은 없는 듯 하니...
우선 그럼 해당 기능은 메인화면 채널목록 기능 구현 후에 다음 features 로 구현하도록 하죠 ㅋㅋ
